sudo: required

services: docker

before_install:
  # docker-composeをinstallすることで１行で済んでいる
  - docker-compose up --build -d
  # log in to Heroku Docker registry
  - docker login -u "$HEROKU_USERNAME" -p "$HEROKU_API_KEY" registry.heroku.com

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test

deploy:

  provider: script
  script:
    # 改行で「;」入れてる
    # buildするhehoku app name. buildするDockerfile名を指定
    docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile.prod .;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku run --app $HEROKU_APP_NAME rails db:migrate;
  on:
    # only deploy is master
    branch: master
